# Generated by Django 5.0.7 on 2024-07-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='original_language',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
